<a href="https://colab.research.google.com/github/MicroprocessorX069/Ensemble-Classifiers-and-Voting/blob/master/EnsembleClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Load MNIST on Python 3.x

In [0]:
import pickle
import gzip
import numpy as np
import matplotlib.pyplot as plt

In [0]:
filename = 'mnist.pkl.gz'
f = gzip.open(filename, 'rb')
training_data, validation_data, test_data = pickle.load(f, encoding='latin1')
f.close()

##Driver

In [0]:
trainData=np.array(training_data[0])
trainResult=np.array(training_data[1])
validationData=np.array(validation_data[0])
validationResult=np.array(validation_data[1])
testData=np.array(test_data[0])
testResult=np.array(test_data[1])
Data=np.concatenate((trainData,validationData,testData),axis=0)

print(Data.shape)
Result=np.concatenate((trainResult,validationResult,testResult),axis=0)
print(Result.shape)
from sklearn.cluster import KMeans
learningRate=0.01
batchSize=10000
train_split=0.9
validation_split=0
no_basisFn=8
features_concat=18
features_subtract=9
m=10
IsSynthetic=False

#Data Contraction
temp=np.array([training_data[1]])
print(training_data[0].shape,temp.shape)
smallTrain=(np.concatenate((training_data[0],temp.T),axis=1))
np.random.shuffle(smallTrain)
smallTrain=smallTrain[0:5000]
print(smallTrain.shape)
smallTrainData=smallTrain[:,0:784]
smallTrainResult=smallTrain[:,784]

temp=np.array([validation_data[1]])
print(validation_data[0].shape,temp.shape)
smallValid=(np.concatenate((validation_data[0],temp.T),axis=1))
np.random.shuffle(smallValid)
smallValid=smallValid[0:500]
print(smallValid.shape)
smallValidData=smallValid[:,0:784]
smallValidResult=smallValid[:,784]

temp=np.array([test_data[1]])
print(test_data[0].shape,temp.shape)
smallTest=(np.concatenate((test_data[0],temp.T),axis=1))
np.random.shuffle(smallTest)
smallTest=smallTest[0:500]
print(smallTest.shape)
smallTestData=smallTest[:,0:784]
smallTestResult=smallTest[:,784]

from sklearn.cluster import KMeans
learningRate=0.01
batchSize=10000
train_split=0.9
validation_split=0
no_basisFn=8
features_concat=18
features_subtract=9
m=10
IsSynthetic=False

#Actual Data
# smallTrainData=trainData
# smallTrainResult=trainResult
# smallValidData=validationData
# smallValidResult=validationResult
# smallTestData=testData
# smallTestResult=testResult

trainData=smallTrainData
trainResult=(smallTrainResult)
validData=smallValidData
validResult=(smallValidResult)
testData=smallTestData
testResultInt=smallTestResult
testResult=(smallTestResult)




(70000, 784)
(70000,)
(50000, 784) (1, 50000)
(5000, 785)
(10000, 784) (1, 10000)
(500, 785)
(10000, 784) (1, 10000)
(500, 785)


#SVM
Kernels:
Kernels are used to transform non separable data to a higher dimensions where it might become separable.

Types of kernels:


In [0]:
from sklearn.svm import SVC 
def SVM(kernelName='rbf'):
  svclassifier = SVC(kernel=kernelName)  
  svclassifier.fit(trainData, trainResult) 
  return svclassifier



Testing data

In [0]:
testPrediction_svm = SVM().predict(testData)  

Evaluation and confusion matrix

In [0]:
from sklearn.metrics import classification_report, confusion_matrix  
import pandas as pd
from sklearn import metrics
print(pd.DataFrame(confusion_matrix(testResult,testPrediction_svm)))  
print(classification_report(testResult,testPrediction_svm))
print("Accuracy:",metrics.accuracy_score(testResult, testPrediction_svm))

In [0]:
USPStestPrediction_svm=SVM().predict(USPSMat)
print(confusion_matrix(USPSTar,USPStestPrediction_svm))
print("Accuracy:",metrics.accuracy_score(USPSTar, USPStestPrediction_svm))

[[ 502    8  433   12  405  249  113   43   15  220]
 [  77  568  144  106  373  228   38  437   16   13]
 [ 136   54 1182   52   63  286   93   94   31    8]
 [  85   13  148  941   29  615   11   83   40   35]
 [  13  163   57    8 1159  292   17  153   62   76]
 [ 101   35  168   70   37 1434   71   60   16    8]
 [ 245   24  333   24  141  477  702   18   12   24]
 [  59  445  383  101   82  442   23  399   38   28]
 [  62   54  176  119  142 1018   98   40  259   32]
 [  31  311  216  183  249  206   10  485  177  132]]
Accuracy: 0.3639181959097955


##Citation
https://stackabuse.com/implementing-svm-and-kernel-svm-with-pythons-scikit-learn/

#Random Forest
Random forest is a combination of decision tree. Where each tree makes a decision and votes for a class. The algorithm then chooses the most popular class as the result. RF can do both, classification and regression. More dense the forest, robust is the process(more accurate).



In [0]:
from sklearn.ensemble import RandomForestClassifier
import time
def RandomForest():
  
  #creating random forest classifier
  #n_estimators are no. of voting decision trees in the forest. More the trees better the final result
  #criterion can be gini or entropy for each of the decision tree and to evaluate the final best split
  #max_features are the no. of features to be looked while evaluating the best split
  #min_samples_leaf doesnot allow any leaf to have less than spcified no. of data samples.

  clf=RandomForestClassifier(n_estimators=100,min_samples_leaf=500)

  #Train the model using the training sets y_pred=clf.predict(X_test)
  clf.fit(trainData,trainResult)
  return clf

In [0]:
from sklearn.metrics import classification_report, confusion_matrix  
from sklearn import metrics
import pandas as pd

rf=RandomForest()
testPrediction_rf=rf.predict(testData)
print(pd.DataFrame(confusion_matrix(testResult,testPrediction_rf)))  
print(classification_report(testResult,testPrediction_rf))
print("Accuracy:",metrics.accuracy_score(testResult, testPrediction_rf))

    0   1   2   3   4  5   6   7   8   9
0  37   0   1   0   0  0   0   0   0   0
1   0  66   0   0   0  0   0   0   0   0
2   4  14  27   1   0  0   1   4   0   0
3   9   7   0  27   0  1   0   2   1   3
4   0   1   0   0  34  0   1   1   0   8
5  15   5   0  11   2  1   1   0   3   9
6   6   3   0   1   1  0  41   1   0   1
7   1   3   1   0   0  0   0  47   0   0
8   2  19   2   4   0  0   0   0  19   4
9   1   2   0   1   1  0   1   3   1  37
             precision    recall  f1-score   support

        0.0       0.49      0.97      0.65        38
        1.0       0.55      1.00      0.71        66
        2.0       0.87      0.53      0.66        51
        3.0       0.60      0.54      0.57        50
        4.0       0.89      0.76      0.82        45
        5.0       0.50      0.02      0.04        47
        6.0       0.91      0.76      0.83        54
        7.0       0.81      0.90      0.85        52
        8.0       0.79      0.38      0.51        50
        9.0       

In [0]:
USPStestPrediction_rf=rf.predict(USPSMat)
print(confusion_matrix(USPSTar,USPStestPrediction_rf))
print("Accuracy:",metrics.accuracy_score(USPSTar, USPStestPrediction_rf))

[[ 686  658    3    2   21    0    0  599    0   31]
 [  84  999    4   21    2    0    2  886    1    1]
 [ 255 1121   38   10    3    0    1  570    0    1]
 [ 315 1260    6   57   10    0    2  339    1   10]
 [ 105 1155    1    9   69    0    0  651    0   10]
 [ 566  971    3   20   15    2    8  399    1   15]
 [ 784  701   12    2    7    0   15  477    0    2]
 [  92 1330    1    1    0    0    0  575    0    1]
 [ 476 1269    6   29   17    0    7  192    1    3]
 [ 128 1098   10   23    8    0    0  730    0    3]]
Accuracy: 0.12225611280564028


Finding the important features.

Random forest also weighs each features according to their importance or contribution in the final result. Here we print the list of top 10 important features because the no of features for this dataset it large

In [0]:
import pandas as pd
feature_imp = pd.Series(clf.feature_importances_).sort_values(ascending=False)
#printing top 10 featurs with their resp. importance
feature_imp.iloc[0:10]

378    0.010522
489    0.008883
406    0.008294
433    0.008112
350    0.008030
211    0.007641
347    0.007358
154    0.007104
405    0.006837
461    0.006812
dtype: float64

##Citations
https://www.datacamp.com/community/tutorials/random-forests-classifier-python
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html


#Logistic Regression

##Functions

In [0]:
def clusterIndices(no_clusters, labels_array): #numpy 
  for cluster_no in range(no_clusters):
    
   return np.where(labels_array == no_clusters)[0]

def GenerateBigSigma(Data, MuMatrix,TrainingPercent,IsSynthetic):
  # To calculate BigSigma as
  #BigSigma 41 x 41
  #Matrix of variances between input features, to calculate PhiMatrix
    '''
                          x(1)      x(2)      x(3) .  .  .     x(41)
    BigSigma =   x(1)  Var(1,1)      0         0                 0

                 x(2)       0      Var(2,2)    0                 0

                 x(3)       0       0        Var(3,3)            0
                  .
                  .
                  .
                 x(41)                                      Var(41,41)
      '''        
    
    #Initializing BigSigma matrix as zeros since we just have to populate the diagonal elements
    
    BigSigma    = np.zeros((len(Data),len(Data))) #shape = 41,41
    DataT       = np.transpose(Data) #len(DataT)=69k 
    TrainingLen = math.ceil(len(DataT)*(TrainingPercent*0.01)) #math ceil return smallest integer less than X, basically converting to nearest bigger int #Len of training data set = 80% of 69k ~ 67k 
    varVect     = []
    
    # Calculating the variance for each input feature, based on training data. np.var return variance of an array
    for i in range(0,len(DataT[0])):
        vct = []
        for j in range(0,int(TrainingLen)):
            vct.append(Data[i][j])    
        varVect.append(np.var(vct)) #Varianance of Data[i,;] i.e. input feature i
    
    #Populating BigSigma Matrix
    for j in range(len(Data)):
        BigSigma[j][j] = varVect[j] ## All other indices other than j,j (i.e. where i != j) would be zero since the covariance between two input features is no required.
    if IsSynthetic == True:         # Use of isSynthetic not known yet
        BigSigma = np.dot(3,BigSigma)
    else:
        BigSigma = np.dot(200,BigSigma)
    ##print ("BigSigma Generated..")
    return BigSigma

def GetScalar(DataRow,MuRow, BigSigInv):  
    #Converts the matrices' (x-Mu), BigSigmaInverse, (x-Mu) product to scalar
    
    #R is (x-Mu); Shape : 1 x 41
    R = np.subtract(DataRow,MuRow)
    #np.transpose(R) is Transpose of (x-Mu); Shape :  41 x 1
    # Shape of BigSigInv is 41 x 41
    # Therefore Shape of T i.e. (R x BigSigmaInverse x Inv(R)): (41) x 41) . (41 x 1)
    #                                                          : 41 x 1 
    T = np.dot(BigSigInv,np.transpose(R))  
    L = np.dot(R,T) #(R . T)
    # Therefore Shape of T i.e. (R x BigSigmaInverse x Inv(R)): (1 x 41). (41) x 41) . (41 x 1)
    #                                                          : 1 x 1 # HenceScalaar
    return L

def GetRadialBasisOut(DataRow,MuRow, BigSigInv):  
  #Calculation of Phi(x)
  #Vector Phi(x) = (-0.5 . (x-Mu) . BigSigmaInverse . (x-Mu))
   #              e
    # math.exp is exponential function e^(x) where x is the argument of the function
    phi_x = math.exp(-0.5*GetScalar(DataRow,MuRow,BigSigInv))
    return phi_x

def GetPhiMatrix(Data, MuMatrix, BigSigma, TrainingPercent = 80):
    #Phi Matrix Shape:  No. of basis fns x Dataset_height i.e. 10 x 67k
    # 10 Basis function matrix applied on 41 input feautres
    '''
    #Phi(x(1)(1/10)) Means Basis function of 1/10 th part of input feature 1 (We divided the input features with kmeans below into 10 clusters)
    
    Vector Phi(x) = (-0.5 . (x-Mu) . BigSigmaInverse . (x-Mu))
                   e
                   
                   
                        Phi1                   Phi2                     Phi3                    .  .  .     Phi10    # no of basis functions i.e. 10
  PhiMatrix=   x(1)   Phi(x(1)(1/10))      Phi(x(1)(2/10))         Phi(x(1)(3/10))     .  .  .        Phi(x(1)(10/10))
  
               x(2)   Phi(x(2)(1/10))      Phi(x(2)(2/10))         Phi(x(2)(3/10))     .  .  .        Phi(x(2)(10/10))
    
               x(3)   Phi(x(3)(1/10))      Phi(x(3)(2/10))         Phi(x(3)(3/10))     .  .  .        Phi(x(3)(10/10))
                .
                .
                .
              x(67k)  Phi(x(67k)(1/10))    Phi(x(67k)(2/10))       Phi(x(67k)(3/10))     .  .  .      Phi(x(67k)(1/10))
    '''        
    DataT = np.transpose(Data)
    TrainingLen = math.ceil(len(DataT)*(TrainingPercent*0.01))         
    PHI = np.zeros((int(TrainingLen),len(MuMatrix))) 
    
    # Calculating inverse of BigSigma matrix for the formula of phi
    BigSigInv = np.linalg.pinv(BigSigma)
    for  C in range(0,len(MuMatrix)):
        for R in range(0,int(TrainingLen)):
            #Calculating Phi of each x1
            PHI[R][C] = GetRadialBasisOut(DataT[R], MuMatrix[C], BigSigInv)
    #print ("PHI Generated..")
    return PHI
  
from keras.utils import np_utils

def encodeOutput(y):
  processed_y=[]
                                                                                 
  for y_label in y:
    if(y_label==0):
      processed_y.append([0])
    elif (y_label==1):
      processed_y.append([1])
    elif (y_label==2):
      processed_y.append([2])
    elif (y_label==3):
      processed_y.append([3])
    elif (y_label==4):
      processed_y.append([4])
    elif (y_label==5):
      processed_y.append([5])
    elif (y_label==6):
      processed_y.append([6])
    elif (y_label==7):
      processed_y.append([7])
    elif (y_label==8):
      processed_y.append([8])
    else:
      processed_y.append([9])
      
  return np.array(np_utils.to_categorical(np.array(processed_y),10))
from sklearn.cluster import KMeans
def LogisticRegression(trainData,trainResult,validData,validResult,testData,testResult,n_classes=10,batch_size=1000,learning_rate=0.1,m=100):
  
  trainResult=encodeOutput(trainResult)
  validResult=encodeOutput(validResult)
  testResultInt=testResult
  testResult=encodeOutput(testResult)
  validation_percent=0
  train_percent=0.9
  IsSynthetic=False
  trainTranspose=np.transpose(trainData)
  kmeans=KMeans(m,random_state=0).fit(trainData)
  means=np.array(kmeans.cluster_centers_)
  variance_mat     = GenerateBigSigma(trainTranspose, means,100 ,IsSynthetic) # generating variance for each input feature
  train_phi = GetPhiMatrix(trainTranspose, means, variance_mat, 100)
  print(train_phi.shape)

  validTranspose=np.transpose(validData)
  kmeans=KMeans(m,random_state=0).fit(validData)
  means=np.array(kmeans.cluster_centers_)
  variance_mat     = GenerateBigSigma(validTranspose, means,100 ,IsSynthetic) # generating variance for each input feature
  valid_phi = GetPhiMatrix(validTranspose, means, variance_mat, 100)
  print(valid_phi.shape)

  testTranspose=np.transpose(testData)
  kmeans=KMeans(m,random_state=0).fit(testData)
  means=np.array(kmeans.cluster_centers_)
  #ClusterIndicesNumpy(7, kmeans.labels_)
  variance_mat     = GenerateBigSigma(testTranspose, means,100 ,IsSynthetic) # generating variance for each input feature
  test_phi = GetPhiMatrix(testTranspose, means, variance_mat, 100)
  print(test_phi.shape)
  result=[]
  for cl in range(0,n_classes):
    result.append(grad_descent(train_phi,trainResult[:,cl],valid_phi,validResult[:,cl],test_phi,testResult[:,cl],batch_size,learning_rate))  
  predictedTestLabel=[]
  result=np.array(result).T
  for rslt in result:
    rslt=list(rslt)
    predictedTestLabel.append(rslt.index(max(rslt)))
  return(np.array(predictedTestLabel))
  #return(np.array(predictedTestLabel))
  
import math

def softmax(x):
    
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0) 
  
def sigmoid(x):
  return 1 / (1 + math.exp(-x))


def getOutput(input_data, weights):
  predicted_result=[]
  for input in input_data:
      output=0
      for i in range(1,len(weights)):
        output=output+weights[i]*input[i-1]
      output=sigmoid(output)
      predicted_result.append(output)
  return(np.array(predicted_result))

def updateWeights(input_data,target_result,predicted_result,prev_weights,learning_rate):
  subtract=np.subtract(predicted_result,target_result)
  weight_change=np.dot(subtract,input_data)
  weight_change/=(input_data.shape[1])
  weight_change*=learning_rate
  new_weights=np.subtract(prev_weights,weight_change)
  return new_weights

def loss(target_result,predicted_result):
  loss=-target_result*np.log(predicted_result)-(1-target_result)*np.log(1-predicted_result)
  loss=loss.sum()/target_result.shape[0]
  return loss
  
def grad_descent(train_phi,trainResult,validation_phi,validationResult,test_phi,testResult,batch_size,learning_rate):
  W=np.zeros(train_phi.shape[1])
  i=0
  loss_arr=[]
  while i+batch_size <= train_phi.shape[0]:
    input_data=train_phi[i:i+batch_size]
    target_result=trainResult[i:i+batch_size]
    i=i+batch_size
    new_lr=learning_rate-(1/i)
    if(new_lr<=0):
      new_lr=learning_rate
    predicted_result=np.round(getOutput(input_data,W))
    validation_predictedResult=np.round(getOutput(validation_phi,W))
    W=updateWeights(input_data,target_result,predicted_result,W,learning_rate)
    loss_arr.append(loss(validationResult,validation_predictedResult))
  test_predictedResult=(getOutput(test_phi,W))
  loss1=loss(testResult,test_predictedResult)
  return(test_predictedResult)   



Using TensorFlow backend.


In [0]:
from sklearn.metrics import classification_report, confusion_matrix  
#0
batch_size=1000
learning_rate=0.1
m=100
n_classes=10
testPrediction_lr=LogisticRegression(trainData,trainResult,validData,validResult,testData,testResult,n_classes,batch_size,learning_rate,m)
confusion_matrix(testResultInt,testPrediction_lr)

(5000, 100)
(500, 100)
(500, 100)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:204: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:204: RuntimeWarning: invalid value encountered in multiply


array([[ 0, 38,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 66,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 51,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 50,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 45,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 47,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 54,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 52,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 50,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 47,  0,  0,  0,  0,  0,  0,  0,  0]])

## Load USPS on Python 3.x

In [0]:
import zipfile
zip_ref = zipfile.ZipFile("USPSdata.zip", 'r')
zip_ref.extractall("USPSData")
zip_ref.close()

In [0]:
from PIL import Image
import os
import numpy as np

In [0]:
USPSMat  = []
USPSTar  = []
curPath  = 'USPSData/USPSdata/Numerals'
savedImg = []

for j in range(0,10):
    curFolderPath = curPath + '/' + str(j)
    imgs =  os.listdir(curFolderPath)
    for img in imgs:
        curImg = curFolderPath + '/' + img
        if curImg[-3:] == 'png':
            img = Image.open(curImg,'r')
            img = img.resize((28, 28))
            savedImg = img
            imgdata = (255-np.array(img.getdata()))/255
            USPSMat.append(imgdata)
            USPSTar.append(j)
USPSMat,USPSTar=np.array(USPSMat),np.array(USPSTar)

In [0]:
USPSMat,USPSTar=np.array(USPSMat),np.array(USPSTar)

#Neural networks

In [0]:
# Neural Network
import keras
from keras.datasets import mnist
from keras.layers import Dense
from keras.models import Sequential
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [0]:
from sklearn.metrics import classification_report, confusion_matrix  
# Neural Network
import keras
from keras.datasets import mnist
from keras.layers import Dense
from keras.models import Sequential
(x_train, y_train), (x_test, y_test) = mnist.load_data()
num_classes=10
image_vector_size=28*28
x_train = x_train.reshape(x_train.shape[0], image_vector_size)
x_test = x_test.reshape(x_test.shape[0], image_vector_size)
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
image_size = 784 
model = Sequential()
model.add(Dense(units=32, activation='sigmoid', input_shape=(image_size,)))
model.add(Dense(units=num_classes, activation='softmax'))
model.compile(optimizer='sgd', loss='categorical_crossentropy',metrics=['accuracy'])
history = model.fit(x_train, y_train, batch_size=128, epochs=10,
verbose=False,validation_split=.1)
loss,accuracy = model.evaluate(x_test, y_test, verbose=False) 

testPrediction=np.array(model.predict(x_test))
testPrediction_nn=[]
for i in range(testPrediction.shape[0]):
  testPrediction_nn.append(testPrediction[i].argmax())

y_test=np.array(y_test)
y_test1=[]
for i in range(y_test.shape[0]):
  y_test1.append(y_test[i].argmax())
  
USPStestPrediction=np.array(model.predict(USPSMat))
USPStestPrediction_nn=[]
for i in range(USPStestPrediction.shape[0]):
  USPStestPrediction_nn.append(USPStestPrediction[i].argmax())

print(confusion_matrix(y_test1,testPrediction_nn))
print("Accuracy:",metrics.accuracy_score(y_test1, testPrediction_nn))

[[ 959    0    5    2    1    3    5    1    4    0]
 [   0 1106    3    5    0    1    3    1   16    0]
 [  17    2  919   15   23    1   11   15   28    1]
 [   5    0   23  918    1   29    1   15   15    3]
 [   1    3    2    1  924    1   13    1    4   32]
 [  18    4    5   63   14  723   22    8   25   10]
 [  25    4    6    1   20   12  884    1    5    0]
 [   6   10   26    4   10    2    0  946    2   22]
 [  11    8   16   30   12   18   10   16  846    7]
 [  14    6    4   16   47    8    0   28    5  881]]
Accuracy: 0.9106


In [0]:
print(confusion_matrix(USPSTar,USPStestPrediction_nn))
print("Accuracy:",metrics.accuracy_score(USPSTar, USPStestPrediction_nn))

[[ 183    4  568  112  116  494   81  109   10  323]
 [   4  162  622  623   68  192   21  273    8   27]
 [   8    6 1403  303   18  173   29   36   13   10]
 [   3    1  151 1579    2  204   12   29    4   15]
 [   2   40  160  157  771  267   19  257   51  276]
 [   7    7  261  328    7 1237   77   61    2   13]
 [  17    4  567  150   57  530  610   13    3   49]
 [   1   36  519  897   10  212    5  278   16   26]
 [   5   10  343  397   50  883   74   71   71   96]
 [   3   81  226  655   59  157   10  488  113  208]]
Accuracy: 0.32511625581279063


In [0]:
print(loss)

0.3633065573692322


#Boosting

Boosting is a technique based on ensemble. It learns on multiple algorithms and weighs its samples which are wrongly classified in the previous algorithm.

In [0]:
from sklearn.metrics import classification_report, confusion_matrix  
from sklearn import metrics
from sklearn import cross_validation
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

import pandas as pd
RandomForest=RandomForestClassifier()
kernel='rbf'
SVM=SVC(kernel='rbf')

#testPrediction_lr=LogisticRegression
for clf,label in zip([RandomForest,SVM],["Random Forest Classifier","Support Vector Classifier"]):
  accuracy=cross_validation.cross_val_score(clf,Data,Result,cv=5,scoring='accuracy')
  print("Accuracy for ",label,": ",accuracy.mean())
  

In [0]:
from sklearn.base import BaseEstimator
from sklearn.base import ClassifierMixin
import numpy as np
import operator

class EnsembleClassifier(BaseEstimator,ClassifierMixin):
  def __init__(self,clfs,weights=None):
    self.clfs=clfs
    self.weights=weights
  
  def fit(self, train_data, train_result):
    for clf in self.clfs:
      clf.fit(train_data,train_result)
  
  def predict(self, train_data):
    
    self.prediction=np.asarray([clf.predict(train_data) for clf in self.clfs])
    if self.weights: # if initial weights are given in the attributes while constructing the object of EnsembleClassifier
      #predict_proba here returns average probabilty for each class for each base classifier according to the weights.
      avg=self.predict_proba(train_data)
      #apply_along_axis applies a function across an array. apply_along_axis(function, axis, array_name)
      #lamda is for defining a function, which returns a result for expression of x, eg.g lambda x: x**3 returns cube of x
      #enumerate function keep a counter or numbers the elements of an array.
      #Finds the classifier which has the best accuracy for the particular class.
      maj=np.apply_along_axis(lambda x:max(enumerate(x),key=operator.itemgetter(1))[0],axis=1,arr=avg)
    else:
      
      maj=np.asarray([np.argmax(np.bitcount(self.prediction[:,c])) for c in range(self.prediction.shape[1])])
    return maj
  
  def predict_proba(self,train_data):
    #predicts probability of correct prediction for each class. eg. 0.8 for class 1(the model predicts class 1 with 80% correctioness), 0.3 for class 2.. and so on
    #predict_proba returns an array of 1 x n_classes. with probability for each classifier
    self.probabs=[clf.predict_proba(train_data) for clf in self.clfs]
    avg=np.average(self.probabs,axis=0,weights=self.weights)
    return avg

In [0]:
from sklearn import cross_validation
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.svm import SVC

import numpy as np

np.random.seed(123)

clf1 = LogisticRegression()
clf2 = RandomForestClassifier(n_estimators=100)
clf3 = SVC(probability=True)

eclf1 = EnsembleClassifier(clfs=[clf1, clf2], weights=[1,1])
scores = cross_validation.cross_val_score(eclf1, smallTrainData, smallTrainResult, cv=5, scoring='accuracy')
print("Accuracy of the ensemble classifier:",scores.mean())


Accuracy of the ensemble classifier: 0.9126014257547779


In [0]:
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
eclf1 = VotingClassifier(estimators=[ ('lr', clf1), ('rf', clf2), ('svc', clf3)], voting='soft')
eclf1 = eclf1.fit(smallTrainData, smallTrainResult)
smallTestPrediction=eclf1.predict(smallTestData)
print(confusion_matrix(smallTestResult,smallTestPrediction))
print("Accuracy:",accuracy_score(smallTestResult, smallTestPrediction))

USPStestPrediction_eclf1=eclf1.predict(USPSMat)
print(confusion_matrix(USPSTar,USPStestPrediction_eclf1))
print("Accuracy:",accuracy_score(USPSTar,USPStestPrediction_eclf1))

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[36  0  1  0  0  0  1  0  0  0]
 [ 0 63  0  0  0  0  0  0  3  0]
 [ 0  0 47  0  2  0  0  1  1  0]
 [ 0  0  0 43  0  1  1  0  5  0]
 [ 0  0  0  0 42  0  0  0  0  3]
 [ 0  1  0  3  0 40  0  0  1  2]
 [ 0  0  0  0  1  1 52  0  0  0]
 [ 0  1  1  0  2  0  0 47  1  0]
 [ 0  0  0  3  0  2  0  0 44  1]
 [ 0  0  0  4  2  0  0  0  1 40]]
Accuracy: 0.908
[[ 535    3  410   55  283  191   66  275   27  155]
 [  56  451  309  199  190   98   25  623   43    6]
 [  97   37 1232  123   56  206   99  108   33    8]
 [  56   13  208 1099   17  434    4   91   53   25]
 [  20   95   92   39  989  230   21  349   98   67]
 [  74   19  296  169   30 1215   65  103   21    8]
 [ 212   13  504   88   94  318  671   48   24   28]
 [ 105  294  357  237   73  279   11  562   53   29]
 [ 182   46  154  279  131  724   80  112  259   33]
 [  21  168  181  379  133  112    8  700  191  107]]
Accuracy: 0.3560178008900445


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [0]:
from sklearn.metrics import classification_report, confusion_matrix  
#LogisticRegression
print("-------Ense")
batch_size=1000
learning_rate=0.1
m=100
n_classes=10
testPrediction_lr=LogisticRegression(trainData,trainResult,validData,validResult,testData,testResult,n_classes,batch_size,learning_rate,m)
print(confusion_matrix(testResultInt,testPrediction_lr))

#Max Voting

In [0]:
import numpy as np
from statistics import mean,mode

import statistics
def mode(list1):
    list_table = statistics._counts(list1)
    len_table = len(list_table)

    if len_table == 1:
        max_mode = statistics.mode(list1)
    else:
        new_list = []
        for i in range(len_table):
            new_list.append(list_table[i][0])
        max_mode = max(new_list) # use the max value here
    return max_mode
  
testPrediction_rf.astype(int)
testPrediction_svm.astype(int)
testPrediction_nn=np.array(testPrediction_nn)
testPrediction_nn.astype(int)
#testPrediction_lr.astype(int)
testPrediction=[]
for i in range(len(testPrediction_rf)):  
  list=[int(testPrediction_rf[i]),int(testPrediction_svm[i]),int(testPrediction_nn[i])]
  temp=int(mode(list))
  if temp:
    testPrediction.append(temp)
  else:
    testPrediction.append(int(mean(list)))
    #print(testPrediction)
print("Accuracy:",accuracy_score(smallTestResult, testPrediction))
print(confusion_matrix(smallTestResult,testPrediction))

Accuracy: 0.734
[[15  8 11  3  0  0  1  0  0  0]
 [ 0 64  0  0  0  0  0  0  2  0]
 [ 0  2 31  1  3  0  2  6  3  3]
 [ 0  2  0 33  3  2  0  5  1  4]
 [ 0  0  0  0 35  0  0  1  0  9]
 [ 0  5  0  3  1 13  4  1  9 11]
 [ 0  0  0  0  0  1 48  1  2  2]
 [ 0  2  1  0  0  1  0 48  0  0]
 [ 0  1  0  2  0  1  0  0 37  9]
 [ 0  0  0  0  1  1  0  1  1 43]]


In [87]:
USPStestPrediction_rf.astype(int)
USPStestPrediction_svm.astype(int)
USPStestPrediction_nn=np.array(USPStestPrediction_nn)
USPStestPrediction_nn.astype(int)
USPStestPrediction_eclf1=np.array(USPStestPrediction_eclf1)
USPStestPrediction_eclf1.astype(int)
#testPrediction_lr.astype(int)
USPStestPrediction=[]
for i in range(len(USPStestPrediction_rf)):  
  list=[int(USPStestPrediction_rf[i]),int(USPStestPrediction_svm[i]),int(USPStestPrediction_nn[i]),int(USPStestPrediction_eclf1[i])]
  temp=int(mode(list))
  if temp:
    USPStestPrediction.append(temp)
  else:
    USPStestPrediction.append(int(mean(list)))
    #print(testPrediction)
print("Accuracy:",accuracy_score(USPSTar, USPStestPrediction))
print(confusion_matrix(USPSTar,USPStestPrediction))

Accuracy: 0.35381769088454423
[[ 245  191  444   55  248  242   87  224   21  243]
 [  10  516  273  154  113  157   29  716   26    6]
 [  48   73 1252  113   41  214   84  133   32    9]
 [  28   29  138 1154   13  442    8  116   44   28]
 [   2  141   84   20  943  246   20  332   80  132]
 [  29   48  233  133   17 1335   63  113   19   10]
 [  20  150  469   78   82  400  678   73   15   35]
 [  13  393  354  209   40  348   16  555   35   37]
 [  12   99  203  218   88  891   91   96  242   60]
 [   3  233  189  325  115  143    8  653  175  156]]


## Citation
https://sebastianraschka.com/Articles/2014_ensemble_classifier.html